/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ship.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[2, 0, 1.5]}>
        <mesh geometry={nodes.Mesh_craft_racer.geometry} material={materials.metal} />
        <mesh geometry={nodes.Mesh_craft_racer_1.geometry} material={materials.metalDark} />
        <mesh geometry={nodes.Mesh_craft_racer_2.geometry} material={materials.dark} />
        <mesh geometry={nodes.Mesh_craft_racer_3.geometry} material={materials.metalRed} />
      </group>
    </group>
  )
}

useGLTF.preload('/ship.glb')
